// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSR8J036ZKp_xJI-DWVsEP4UkESHotzsw',
    appId: '1:343320436172:web:9412dd8c731649bab09169',
    messagingSenderId: '343320436172',
    projectId: 'health-surveillance-system',
    authDomain: 'health-surveillance-system.firebaseapp.com',
    storageBucket: 'health-surveillance-system.firebasestorage.app',
    measurementId: 'G-84HXP3L863',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIQkdnRZsZedEyNQGmsAlHseCg4LH5Kkw',
    appId: '1:343320436172:android:54b8b72ef5e1bc48b09169',
    messagingSenderId: '343320436172',
    projectId: 'health-surveillance-system',
    storageBucket: 'health-surveillance-system.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeSGARAYUpP5q4diGk8eJ5ifT8ewnorbQ',
    appId: '1:343320436172:ios:5094a34088e7d6a1b09169',
    messagingSenderId: '343320436172',
    projectId: 'health-surveillance-system',
    storageBucket: 'health-surveillance-system.firebasestorage.app',
    iosBundleId: 'com.example.healthSurveillanceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeSGARAYUpP5q4diGk8eJ5ifT8ewnorbQ',
    appId: '1:343320436172:ios:5094a34088e7d6a1b09169',
    messagingSenderId: '343320436172',
    projectId: 'health-surveillance-system',
    storageBucket: 'health-surveillance-system.firebasestorage.app',
    iosBundleId: 'com.example.healthSurveillanceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSR8J036ZKp_xJI-DWVsEP4UkESHotzsw',
    appId: '1:343320436172:web:254edb0787d56e12b09169',
    messagingSenderId: '343320436172',
    projectId: 'health-surveillance-system',
    authDomain: 'health-surveillance-system.firebaseapp.com',
    storageBucket: 'health-surveillance-system.firebasestorage.app',
    measurementId: 'G-LZ951PRF0P',
  );

}