name: health_surveillance_app
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
 
  # Firebase Services
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  cloud_firestore: ^4.15.8
  firebase_messaging: ^14.7.19
  firebase_storage: ^11.6.9

  # UI & Utility Packages
  cupertino_icons: ^1.0.8
  flutter_vector_icons: ^2.0.0
  google_fonts: ^6.2.1
  intl: ^0.19.0
  fl_chart: ^0.68.0
  flutter_local_notifications: ^17.0.0
  provider: ^6.1.2
  geolocator: ^11.0.0
  url_launcher: ^6.2.6
  image_picker: ^1.0.7
  http: ^1.2.1
  pdf: ^3.10.8
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  open_file: ^3.3.2

    # 1. Add OpenStreetMap packages
  flutter_map: ^6.1.0
  latlong2: ^0.9.1
  flutter_map_marker_cluster: ^1.3.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

# This is the single, corrected flutter section
flutter:
  uses-material-design: true
  assets:
    # Declare the specific font files needed by the PDF generator
    # Paths updated to match your folder structure
    - assets/fonts/Poppins/Poppins-Regular.ttf
    - assets/fonts/Poppins/Poppins-Bold.ttf
    - assets/fonts/Poppins/Poppins-ExtraBold.ttf

